seed: 1
device: "cpu"

# RL params
gamma: 0.99
rl_test_episodes: 100000
n_actions: 7
metacontroller: 'multiagent'

# Learning params
batch_size: 256
update_every: 50

# Logistics params
save_model_episode: 10000
visualize_every: 10000  # how many episodes before making a video
log_episode: 500
log_step: 1000
version: "default"
print_every: 10
base_save_path: ''

# architecture
fc_direction: 8
cumulants: 64
filters: 32
kernel_size: 3
fc: 256
lstm_hidden_size: 256
k1: 50
k2: 10
input_dim: 79
action_dim: 7
rnd_hidden_size: 256
rnd_output_size: 64
rnd_learning_rate: 0.001
torch_deterministic: True
